package by.korzun.spotify_spring_console.service;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.time.YearMonth;
import java.util.InputMismatchException;
import java.util.Scanner;

@Service
@RequiredArgsConstructor
public class ConsoleApplicationAssembler implements CommandLineRunner {
    private static final Scanner COMMAND_SCANNER = new Scanner(System.in);

    private final TrackHistoryService trackHistoryService;

    @Override
    public void run(String... args) {
        int running = 1;
        System.out.println("Welcome to my Spotify clone! What's interesting to you?");
        while(running == 1) {

            System.out.println("1 - a playlist of top tracks of this month");
            System.out.println("2 - a playlist of top tracks of previous month");
            System.out.println("3 - a playlist generated by us ;)");
            System.out.println("4 - quit");

            try {
                switch (COMMAND_SCANNER.nextInt()) {
                    case 1:
                        showInConsoleTopTracksOfTheMonth();
                        break;
                    case 2:
                        showInConsoleTopTracksOfPreviousMonth();
                        break;
                    case 3:
                        showInConsoleRandomTracks();
                        break;
                    case 4:
                        running = 0;
                        break;
                    default:
                        System.err.println("There is an error. Please enter correct number.");
                        break;
                }
            } catch (InputMismatchException exception) {
                System.err.println("Please, enter a number.");
                COMMAND_SCANNER.next();
            }
        }
        COMMAND_SCANNER.close();
    }

    private void showInConsoleTopTracksOfPreviousMonth() {
        trackHistoryService.getPlaylistOfTopTracksOfTheMonthWithoutCachedTracks(YearMonth.now())
                .getTracks()
                .forEach(System.out::println);
    }

    private void showInConsoleTopTracksOfTheMonth() {
        trackHistoryService.getPlaylistOfTopTracksOfTheMonth(YearMonth.now())
                .getTracks()
                .forEach(System.out::println);
    }

    private void showInConsoleRandomTracks() {
        trackHistoryService.getRandomTracks(YearMonth.now())
                .getTracks()
                .forEach(System.out::println);
    }
}
